### ISSUE TITLE
centos 8 stream: mysql   8.0.17  make errros.  MYSQL  name conflict

### ISSUE THREAD

**Issue by suisou** [gittiver/litesql#3]
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:108:8: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
 struct MYSQL;
        ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:115:58: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
   int (*authenticate_user)(MYSQL_PLUGIN_VIO *vio, struct MYSQL *mysql);
                                                          ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:117:65: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
                                                          struct MYSQL *mysql,
                                                                 ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:139:57: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
 struct st_mysql_client_plugin *mysql_load_plugin(struct MYSQL *mysql,
                                                         ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:159:59: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
 struct st_mysql_client_plugin *mysql_load_plugin_v(struct MYSQL *mysql,
                                                           ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:173:64: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
 struct st_mysql_client_plugin *mysql_client_find_plugin(struct MYSQL *mysql,
                                                                ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from /usr/include/mysql/mysql.h:84,
                 from mysql.cpp:17:
/usr/include/mysql/mysql/client_plugin.h:192:12: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
     struct MYSQL *mysql, struct st_mysql_client_plugin *plugin);
            ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from mysql.cpp:17:
/usr/include/mysql/mysql.h:294:16: error: using typedef-name â€˜MYSQLâ€™ after â€˜structâ€™
 typedef struct MYSQL {
                ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: â€˜MYSQLâ€™ has a previous declaration here
 typedef struct st_mysql MYSQL;
                         ^~~~~
In file included from mysql.cpp:17:
/usr/include/mysql/mysql.h:332:3: error: conflicting declaration â€˜typedef int MYSQLâ€™
 } MYSQL;
   ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:25: note: previous declaration as â€˜typedef struct st_mysql MYSQLâ€™
 typedef struct st_mysql MYSQL;
                         ^~~~~
mysql.cpp: In constructor â€˜litesql::MySQL::MySQL(const string&)â€™:
mysql.cpp:83:5: error: â€˜Splitâ€™ was not declared in this scope
     Split params(connInfo,";");
     ^~~~~
mysql.cpp:86:28: error: â€˜paramsâ€™ was not declared in this scope
     for (size_t i = 0; i < params.size(); i++) {
                            ^~~~~~
mysql.cpp:87:14: error: expected â€˜;â€™ before â€˜paramâ€™
         Split param(params[i], "=");
              ^~~~~~
              ;
mysql.cpp:88:13: error: â€˜paramâ€™ was not declared in this scope
         if (param.size() == 1)
             ^~~~~
mysql.cpp:90:13: error: â€˜paramâ€™ was not declared in this scope
         if (param[0] == "host")
             ^~~~~
mysql.cpp:101:16: error: invalid use of incomplete type â€˜MYSQLâ€™ {aka â€˜struct st_mysqlâ€™}
     conn = new MYSQL;
                ^~~~~
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:16: note: forward declaration of â€˜MYSQLâ€™ {aka â€˜struct st_mysqlâ€™}
 typedef struct st_mysql MYSQL;
                ^~~~~~~~
mysql.cpp: In destructor â€˜virtual litesql::MySQL::~MySQL()â€™:
mysql.cpp:111:12: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     delete conn;
            ^~~~
mysql.cpp:111:12: warning: invalid use of incomplete type â€˜struct st_mysqlâ€™
In file included from mysql.cpp:7:
./../../include/mysql.hpp:20:16: note: forward declaration of â€˜struct st_mysqlâ€™
 typedef struct st_mysql MYSQL;
                ^~~~~~~~
mysql.cpp:111:12: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     delete conn;

**Comment by gittiver** [comment]
auto tools build is not supported anymore, please try cmake build.
