### ISSUE TITLE
Cursor issue

### ISSUE THREAD

**Issue by roman30rus** [gittiver/litesql#4]
Hello i have error on compile that code:
Cursor<Record> cur = db.cursor<Record>(SelectQuery().result("name_").source("Group_"));
for (;!cur.rowsLeft(); cur++) { cout << (*cur).data()->c_str()  << endl; }

////////////////////////////////////////

C:\Users\Admin\Projects\Test\LiteSQL\include\litesql.hpp:11: In file included from ..\Test\LiteSQL\include/litesql.hpp:11:0,
In file included from ..\Test\LiteSQL\include/litesql.hpp:11:0,
                 from ..\Test\globals.h:10,
                 from ..\Test\productAdd.h:2,
                 from ..\Test\productAdd.cpp:1:
..\Test\LiteSQL\include/litesql/types.hpp:23:5: note: candidate: litesql::Record::Record(size_t)
     Record(size_t reserved) { reserve(reserved); }
     ^~~~~~
..\Test\LiteSQL\include/litesql/types.hpp:23:5: note:   candidate expects 1 argument, 2 provided
..\Test\LiteSQL\include/litesql/types.hpp:22:5: note: candidate: litesql::Record::Record()
     Record() : std::vector<std::string>() {}
     ^~~~~~
..\Test\LiteSQL\include/litesql/types.hpp:22:5: note:   candidate expects 0 arguments, 2 provided
..\Test\LiteSQL\include/litesql/types.hpp:19:7: note: candidate: litesql::Record::Record(const litesql::Record&)
 class Record : public std::vector<std::string>
       ^~~~~~
..\Test\LiteSQL\include/litesql/types.hpp:19:7: note:   candidate expects 1 argument, 2 provided
..\Test\LiteSQL\include/litesql/types.hpp:19:7: note: candidate: litesql::Record::Record(litesql::Record&&)
..\Test\LiteSQL\include/litesql/types.hpp:19:7: note:   candidate expects 1 argument, 2 provided

**Comment by gittiver** [comment]
Can you attach the Code you used to compile the sample?

**Comment by gittiver** [comment]
As I never got the code for the bug, I will close the issue
