### ISSUE TITLE
postgresql error : DatabaseError: could not load plugin

### ISSUE THREAD

**Issue by atalia** [gittiver/litesql#5]
Modify the database type in the example to postgresql:
```c++
ExampleDatabase db("postgresql", "host=localhost;database=test-update-table;user=litesql;password=litesql");
```
got this error：
```
joo
liblitesql_backend_postgresql.so: cannot open shared object file: No such file or directory
DatabaseError: could not load plugin
```
is it possible to support litesql_postgresql_backend lib?

**Comment by gittiver** [comment]
is the library liblitesql_backend_postgresql.so built? 
if yes, then try to add its path to $LD_LIRARY_PATH like this:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/custom/path/
```

**Comment by atalia** [comment]
At tag Version_0.3.18. I cannot control liblitesql_backend_postgresql.so compilation in cmakelists.txt. 
how to build liblitesql_backend_postgresql.so ?

**Comment by atalia** [comment]
> is the library liblitesql_backend_postgresql.so built? if yes, then try to add its path to $LD_LIRARY_PATH like this:
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/custom/path/
> ```

At tag Version_0.3.18. I cannot control liblitesql_backend_postgresql.so compilation in cmakelists.txt.
how to build liblitesql_backend_postgresql.so ?
